name: Deploy

on:
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  deploy-maven:
    name: Build & Deploy to GitHub packages (Maven)
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: 21
          cache: maven

      - name: Setup Maven
        uses: stCarolas/setup-maven@v5.1
        with:
          maven-version: 3.9.9

      - name: Generate Maven settings.xml
        run: |
          mkdir -p ~/.m2
          
          cat <<'EOF' > ~/.m2/settings.xml
          <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 http://maven.apache.org/xsd/settings-1.0.0.xsd">

            <servers>
              <server>
                <id>scmdb</id>
                <username>token</username>
                <password>${env.GITHUB_TOKEN}</password>
              </server>
            </servers>

            <profiles>
              <profile>
                <id>scmdb</id>
                <repositories>
                  <repository>
                    <id>scmdb</id>
                    <name>scmdb</name>
                    <url>https://maven.pkg.github.com/${env.GITHUB_REPOSITORY}</url>
                  </repository>
                </repositories>
              </profile>
            </profiles>
          </settings>
          EOF

      - name: Extract version from project
        id: get_version
        run: |
          VERSION="$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
          echo "version=${VERSION}" >> "${GITHUB_OUTPUT}"

      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: mvn package deploy -P scmdb "-DaltDeploymentRepository=scmdb::https://maven.pkg.github.com/$GITHUB_REPOSITORY"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          path: target/scmdb.jar
          retention-days: 2
          if-no-files-found: error
          archive: false

  deploy-container:
    needs:
      - deploy-maven
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download build artifact
        uses: actions/download-artifact@v8
        with:
          name: scmdb.jar
          skip-decompress: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: token
          password: ${{ github.token }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/onevizion/scmdb/scmdb:${{ needs.deploy-maven.outputs.version }}
